//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCMidiTransfarSystem {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCMidiTransfarSystem.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button {
            get {
                return ResourceManager.GetString("button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSCOptionSetting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkbox1 {
            get {
                return ResourceManager.GetString("checkbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display a message in VRChat
        ///when connection is successful に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkbox2 {
            get {
                return ResourceManager.GetString("checkbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ConnectionError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string credit {
            get {
                return ResourceManager.GetString("credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRCMidiTransgerSystem（VMTS）Ver1.0
        ///Copyright © 2025 スパイル (spire)
        ///This software is provided under the MIT License.
        ///https://opensource.org/license/mit
        ///
        ///Creator
        ///https://x.com/spire_fily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string credittext {
            get {
                return ResourceManager.GetString("credittext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string disconnection {
            get {
                return ResourceManager.GetString("disconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to disconnect MIDI device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string disconnection_failed {
            get {
                return ResourceManager.GetString("disconnection failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DisconnectionError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string disconnectionError {
            get {
                return ResourceManager.GetString("disconnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDISetting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string groupbox1 {
            get {
                return ResourceManager.GetString("groupbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRChat OSCSetting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string groupbox2 {
            get {
                return ResourceManager.GetString("groupbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illegal Signal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string illegal_signal {
            get {
                return ResourceManager.GetString("illegal signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIDevices に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIReceptionLog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPAdress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PortNumber に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ConnectionSuccessful. VMTS Ver1.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open MIDI device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenError {
            get {
                return ResourceManager.GetString("OpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDI reception failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string reception_failed {
            get {
                return ResourceManager.GetString("reception failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to stop MIDI device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StopError {
            get {
                return ResourceManager.GetString("StopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strength に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string strength {
            get {
                return ResourceManager.GetString("strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hh:mm:ss tt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
